/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Multis;
using Server.Mobiles;
using Server.Targeting;

namespace Server.Items
{
	public class PsychoShowerLeftWallAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PsychoShowerLeftWallAddonDeed();
			}
		}

		[ Constructable ]
		public PsychoShowerLeftWallAddon()
		{
			AddComponent( new AddonComponent( 4652 ), -1, 0, 1 );
			AddComponent( new AddonComponent( 1299 ), -1, 0, 1 );
			AddComponent( new AddonComponent( 698 ), -1, 0, 1 );
			AddComponent( new AddonComponent( 1299 ), -1, 0, 1 );
			AddComponent( new AddonComponent( 698 ), -1, 0, 1 );
			AddComponent( new AddonComponent( 5534 ), -1, 1, 1 );
			AddComponent( new AddonComponent( 5534 ), -1, 1, 1 );
			AddComponent( new AddonComponent( 7424 ), -1, -2, 1 );
			AddComponent( new AddonComponent( 1300 ), -1, -2, 1 );
			AddComponent( new AddonComponent( 1300 ), -1, -2, 1 );
			AddComponent( new AddonComponent( 4653 ), -1, -1, 1 );
			AddComponent( new AddonComponent( 1299 ), -1, -1, 1 );
			AddComponent( new AddonComponent( 5154 ), -1, -1, 1 );
			AddComponent( new AddonComponent( 6194 ), -1, -1, 16 );
			AddComponent( new AddonComponent( 1299 ), -1, -1, 1 );
			AddComponent( new AddonComponent( 5154 ), -1, -1, 1 );
			AddComponent( new AddonComponent( 6194 ), -1, -1, 16 );
			AddComponent( new AddonComponent( 7572 ), -1, -1, 1 );
			AddComponent( new AddonComponent( 4269 ), 2, -1, 10 );
			AddComponent( new AddonComponent( 4269 ), 2, -1, 10 );
			AddComponent( new AddonComponent( 1300 ), 1, -2, 1 );
			AddComponent( new AddonComponent( 699 ), 1, -2, 1 );
			AddComponent( new AddonComponent( 1300 ), 1, -2, 1 );
			AddComponent( new AddonComponent( 699 ), 1, -2, 1 );
			AddComponent( new AddonComponent( 1299 ), 1, -1, 1 );
			AddComponent( new AddonComponent( 699 ), 1, -1, 1 );
			AddComponent( new AddonComponent( 1299 ), 1, -1, 1 );
			AddComponent( new AddonComponent( 699 ), 1, -1, 1 );
			AddComponent( new AddonComponent( 1300 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 697 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 660 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 1300 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 697 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 660 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 4272 ), 1, 1, 10 );
			AddComponent( new AddonComponent( 4272 ), 1, 1, 10 );
			AddComponent( new AddonComponent( 4269 ), 2, 0, 10 );
			AddComponent( new AddonComponent( 4269 ), 2, 0, 10 );
			AddComponent( new AddonComponent( 5534 ), -1, 2, 1 );
			AddComponent( new AddonComponent( 4828 ), 2, -2, 1 );
			AddComponent( new AddonComponent( 4828 ), 2, -2, 1 );
			AddComponent( new AddonComponent( 1300 ), 0, -1, 1 );
			AddComponent( new AddonComponent( 1300 ), 0, -1, 1 );
			AddComponent( new AddonComponent( 4650 ), 0, -2, 1 );
			AddComponent( new AddonComponent( 1299 ), 0, -2, 1 );
			AddComponent( new AddonComponent( 3837 ), 0, -2, 0 );
			AddComponent( new AddonComponent( 3625 ), 0, -2, 3 );
			AddComponent( new AddonComponent( 1299 ), 0, -2, 1 );
			AddComponent( new AddonComponent( 3837 ), 0, -2, 0 );
			AddComponent( new AddonComponent( 3625 ), 0, -2, 3 );
			AddComponent( new AddonComponent( 7573 ), 0, -2, 1 );
			AddComponent( new AddonComponent( 4839 ), 0, 1, 1 );
			AddComponent( new AddonComponent( 4272 ), 0, 1, 10 );
			AddComponent( new AddonComponent( 4839 ), 0, 1, 1 );
			AddComponent( new AddonComponent( 4272 ), 0, 1, 10 );
			AddComponent( new AddonComponent( 7431 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 1 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 1299 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 698 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 1299 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 698 ), 0, 0, 1 );
			AddonComponent ac = null;
			ac = new AddonComponent( 4652 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 7431 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 7424 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 4650 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 4653 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 7572 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 7573 );
			AddComponent( ac, 0, -2, 1 );

		}

		public PsychoShowerLeftWallAddon( Serial serial ) : base( serial )
		{
		}

		public override void OnDoubleClick( Mobile from )
		{
			BaseHouse house = BaseHouse.FindHouseAt( this );

			if ( house != null && house.IsCoOwner( from ) )
			{
				if ( from.InRange( GetWorldLocation(), 3 ) )
				{
					from.AddToBackpack( new PsychoShowerLeftWallAddonDeed() );
					Delete();
				}
				else
				{
					from.SendLocalizedMessage( 500295 ); // You are too far away to do that.
				}
			}
		}
		
		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PsychoShowerLeftWallAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PsychoShowerLeftWallAddon();
			}
		}

		[Constructable]
		public PsychoShowerLeftWallAddonDeed()
		{
			Name = "PsychoShowerLeftWall";
		}

		public PsychoShowerLeftWallAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}