/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Multis;
using Server.Mobiles;
using Server.Targeting;

namespace Server.Items
{
	public class ShowerRightWallAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShowerRightWallAddonDeed();
			}
		}

		[ Constructable ]
		public ShowerRightWallAddon()
		{
			AddComponent( new AddonComponent( 699 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 699 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 672 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 4272 ), 0, 2, 8 );
			AddComponent( new AddonComponent( 4269 ), 0, 1, 10 );
			AddComponent( new AddonComponent( 698 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 1299 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 4269 ), 0, 0, 10 );
			AddComponent( new AddonComponent( 3837 ), 0, 0, 4 );
			AddComponent( new AddonComponent( 5154 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 1299 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 4828 ), 0, -1, 1 );
			AddComponent( new AddonComponent( 1300 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 3625 ), 0, -1, 1 );
			AddComponent( new AddonComponent( 1299 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 1300 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 4839 ), 3, 2, 0 );
			AddComponent( new AddonComponent( 1300 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 698 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 5535 ), -2, -1, 0 );
			AddComponent( new AddonComponent( 698 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 1299 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 4272 ), 1, 2, 8 );
			AddComponent( new AddonComponent( 1299 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 6197 ), 1, -1, 15 );
			AddComponent( new AddonComponent( 5155 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 1300 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 699 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 5535 ), -1, -1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 4269 );
			ac.Hue = 961;
			AddComponent( ac, 0, 1, 10 );
			ac = new AddonComponent( 4269 );
			ac.Hue = 961;
			AddComponent( ac, 0, 0, 10 );
			ac = new AddonComponent( 3837 );
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 5154 );
			ac.Hue = 946;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4828 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 699 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 699 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 698 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 698 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1300 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1299 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1300 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1300 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1299 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1299 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1299 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1300 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1299 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3625 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 6197 );
			AddComponent( ac, 1, -1, 15 );
			ac = new AddonComponent( 5155 );
			ac.Hue = 946;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 5535 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 699 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 698 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 672 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 5535 );
			AddComponent( ac, -2, -1, 0 );

		}

		public ShowerRightWallAddon( Serial serial ) : base( serial )
		{
		}

		public override void OnDoubleClick( Mobile from )
		{
			BaseHouse house = BaseHouse.FindHouseAt( this );

			if ( house != null && house.IsCoOwner( from ) )
			{
				if ( from.InRange( GetWorldLocation(), 3 ) )
				{
					from.AddToBackpack( new ShowerRightWallAddonDeed() );
					Delete();
				}
				else
				{
					from.SendLocalizedMessage( 500295 ); // You are too far away to do that.
				}
			}
		}
		
		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ShowerRightWallAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShowerRightWallAddon();
			}
		}

		[Constructable]
		public ShowerRightWallAddonDeed()
		{
			Name = "ShowerRightWall";
		}

		public ShowerRightWallAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}